name: Java tests with gradle

on:
    push:
      branches: [ main ]
    pull_request:
      branches: [ main ]

jobs:
    build:

      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v2
        - name: Set up JDK 15
          uses: actions/setup-java@v2
          with:
            java-version: '15'
            distribution: 'adopt'
          - name: clean build
            run: ./gradlew clean build --info --stacktrace
          - name: Run Backend Tests
            run: ./gradlew test
